utils::globalVariables(c("moderation_data", "pca_degenerate"))

#' Degenerate PCA demo dataset
#'
#' A small two-column dataset used to demonstrate a degenerate PCA case where
#' the variance is concentrated almost entirely along one axis, producing a
#' near-singular principal component structure.
#'
#' @format A data frame with 16 rows and 2 numeric columns:
#' \describe{
#'   \item{x}{Horizontal coordinate.}
#'   \item{y}{Vertical coordinate.}
#' }
#'
#' @examples
#' head(pca_degenerate)
"pca_degenerate"


#' Synthetic moderation dataset
#'
#' A bundled synthetic dataset calibrated to show a clear interaction
#' (moderation) effect when visualised as a 3D wireframe surface. Used as the
#' default \code{data} argument for \code{\link{plot_moderation_3d}} and
#' \code{\link{interactive_moderation_3d}}, so that calling either function
#' with no arguments produces a working classroom demonstration.
#'
#' @format A data frame with 200 rows and 4 numeric columns:
#' \describe{
#'   \item{y}{Outcome (dependent variable).}
#'   \item{x}{Independent variable.}
#'   \item{z}{Moderator.}
#'   \item{w}{Unrelated noise predictor — drawn independently of \code{x},
#'     \code{z}, and \code{y}. Any correlation with \code{y} is spurious.
#'     Useful for demonstrating that irrelevant predictors do not change
#'     the IV/mod surface and for exercising the multi-predictor
#'     \code{iv}/\code{mod} arguments of \code{\link{plot_moderation_3d}}.}
#' }
#'
#' @details
#' Generated as \code{y = 0.5*x + 0.3*z + 0.8*(x*z) + N(0, 1)} with
#' \code{x, z, w ~ N(0, 2)} drawn independently, \code{n = 200}, and
#' \code{set.seed(42)}.
#'
#' Variable names follow the moderation-literature convention (Aiken & West)
#' where \code{y} is the outcome, \code{x} is the independent variable, and
#' \code{z} is the moderator. Note that in 3D wireframe plots the *vertical*
#' plot axis depicts the outcome \code{y} regardless of variable naming.
#'
#' @source Generated by \code{data-raw/moderation_data.R}. Purely synthetic.
#'
#' @examples
#' head(moderation_data)
#' summary(lm(y ~ x * z, data = moderation_data))
#' summary(lm(y ~ w, data = moderation_data))  # w is noise — no real effect
"moderation_data"
